In [5]:
import torch
import torch as th
import tensorflow as tf
import datetime as dt
# import matplotlib.pyplot as plt
# %matplotlib inline

In [6]:
x = th.rand(2,2)
print(x)
print(th.cuda.is_available())
# print(th.rand(2,2).cuda())
# d = dt.date(year = 2021, month = 1, day = 1)
# print(d.month)
# print(d.strftime('%Y %m%d'))

# plt.plot([4,2,3,7,1])

import tensorflow as tf
tf.test.is_gpu_available()

tensor([[0.4287, 0.2186],
        [0.0296, 0.2894]])
True


True

In [7]:
import tensorflow as tf
# tf.test.is_gpu_available()
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [8]:
import numpy as np
data = np.array([1,2,3])
type(data)

numpy.ndarray

In [9]:
torch.Tensor(data)

tensor([1., 2., 3.])

In [10]:
torch.tensor(data)

tensor([1, 2, 3], dtype=torch.int32)

In [11]:
torch.as_tensor(data)

tensor([1, 2, 3], dtype=torch.int32)

In [12]:
torch.from_numpy(data)

tensor([1, 2, 3], dtype=torch.int32)

In [13]:
torch.from_numpy(data)

tensor([1, 2, 3], dtype=torch.int32)

In [14]:
t = torch.ones([2,2])
print(t)

tensor([[1., 1.],
        [1., 1.]])


In [15]:
t.reshape(1,4)

tensor([[1., 1., 1., 1.]])

In [16]:
t.reshape(1,4).squeeze()

tensor([1., 1., 1., 1.])

In [17]:
def flatten1try(t):
    t = t.reshape(1,-1)
    t = t.squeeze()
    return t

In [18]:
flatten1try(t)

tensor([1., 1., 1., 1.])

In [19]:
t1 = torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])

t2 = torch.tensor([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2]
])

t3 = torch.tensor([
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3]
])
print(t1,t2,t3)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]) tensor([[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]]) tensor([[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]])


In [20]:
t = torch.stack((t1,t2,t3))
print(t)
t.shape

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])


torch.Size([3, 4, 4])

In [21]:
t = t.reshape(3,1,4,4)
print(t)

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])


In [22]:
print(t.flatten(start_dim = 1))
t222 = t.flatten(start_dim = 1)
print(t222.reshape(3,1,4,4))
print(t.reshape(3,-1))

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])
tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])
